### PR TITLE
Bump version / Tidy

### PR DESCRIPTION
**Pull request by S33G**

### CODE REVIEW

**Review by Irishstevie — APPROVED** [review]
Bump version would help with support

**Review by Z3rio — APPROVED** [review]
This would indeed be great for support purposes.

**Review by Z3rio — APPROVED** [review]

**Review by GhzGarage — APPROVED** [review]

**Comment by charj** [comment]
Can this be merged?

**Review by Irishstevie — APPROVED** [review]

**Comment by zwkf** [comment]
Unable to merge this due to github perms being weird

**Review by zwkf — COMMENTED** [review]
Still unable to merge

**Comment by zwkf** [comment]
I still can't merge this

**Pull request closed without merging**
