### PR TITLE
V2

### PR DESCRIPTION
**Pull request by BerkieBb**
This needs **testing**

### CODE REVIEW

**Comment by IllInuz** [comment]
Seem to be getting some error with :

`lua
local function round(value, numDecimalPlaces)
	if not numDecimalPlaces then return math.floor(value + 0.5) end
    local power = 10 ^ numDecimalPlaces
    return math.floor((value * power) + 0.5) / (power)
end`

The actual line triggering it is within the clientside;

`lua
				if round(current.currentHeading, 0) == round(current.objYaw or current.objHeading, 0) then
					DoorSystemSetDoorState(current.doorHash, 4, false, false)
				end
`

Haven't looked in to it, as to why it does it, just saw it after a testrun with it, other then that looks to be running smooth!
Nice contribution berkie!

**Comment by BerkieBb** [comment]
The latest commit should fix it if you made a new door

**Comment by IdrisDose** [comment]
Is this ready to go?

**Review by jay-fivem — APPROVED** [review]
Didn't have any problems when I tested.

**Pull request merged**
