### PR TITLE
add doorid for text

### PR DESCRIPTION
**Pull request by evanillaa**

### CODE REVIEW

**Comment by zfbx** [comment]
What's the purpose of this? for debug?

**Comment by evanillaa** [comment]
To know the door number in case the maps are modified

**Comment by zfbx** [comment]
Then in that case I'd suggest putting this behind a debug mode variable. I don't think the IDs should just be there all the time because it'll confuse people

**Comment by evanillaa** [comment]
Thank you for the interaction, it is important that we get to the good code
All thanks to you

**Comment by tomasalves8** [comment]
Unless this is changed to a debug mode, I believe this can be closed.

**Pull request closed without merging**
